import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {


    public static void main(String[] args) throws FileNotFoundException {
        File file = new File("mainproject/src/main/resources/myfile.txt");
        Scanner readfile = new Scanner(file);
        int a = Integer.parseInt(readfile.next());
        int b = Integer.parseInt(readfile.next());
        System.out.println("Commit #2");
        System.out.println("Result nod = " + Evklid.nok(a,b));
        System.out.println("Result nok = " + SupportEvklid.nod(a,b));
    }
}
